### ISSUE TITLE
 ImportError: No module named brother_ql.create

### ISSUE THREAD

**Issue by medouederni** [pklaus/brother_ql#1]
I installed brother_ql on Raspberry Pi 2 (Raspbian).
**I test the main cmd:**
$ brother_ql_create --model QL-500 ./720x300_monochrome.png > 720x300_monochrome.bin

**and got this error:**

Traceback (most recent call last):
  File "/usr/local/bin/brother_ql_create", line 9, in <module>
    load_entry_point('brother-ql==0.6-dev', 'console_scripts', 'brother_ql_create')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named brother_ql.create

**Comment by pklaus** [comment]
Thanks. This problem is a convolution of using Python 2 (I used / tested it against Python 3) and of a bug in the raster command file creation process.
Both problems will be fixed in a minute: I'll push the necessary commits. Try again after upgrading the package with `pip install https://github.com/pklaus/brother_ql/archive/master.zip --upgrade`
