### ISSUE TITLE
OSError: [Errno 22] Invalid argument When Sending Instructions

### ISSUE THREAD

**Issue by brianFruit** [pklaus/brother_ql#129]
It's happening in my Raspberry Pi 3 connected to a QL-800 via USB. I'm suspecting it's dependency issues, but I'm not sure where to find the exact versions needed for the dependencies.  

My test snippet
```
import brother_ql
from brother_ql.conversion import convert
from brother_ql.raster import BrotherQLRaster
from brother_ql.backends.helpers import send, discover
from PIL import Image

im = Image.open('./test.jpg')
im = im.resize((696, 271))

PRINTER_IDENTIFIER = '/dev/bus/usb/001/011'
qlr = BrotherQLRaster("QL-800")
qr_data = convert(qlr, [im], "62x29")
send(instructions=qr_data, printer_identifier=PRINTER_IDENTIFIER, backend_identifier="linux_kernel")
```

Full Trace
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    send(instructions=qr_data, printer_identifier=PRINTER_IDENTIFIER, backend_identifier="linux_kernel")
  File "/usr/local/lib/python3.7/dist-packages/brother_ql/backends/helpers.py", line 61, in send
    printer.write(instructions)
  File "/usr/local/lib/python3.7/dist-packages/brother_ql/backends/generic.py", line 34, in write
    self._write(data)
  File "/usr/local/lib/python3.7/dist-packages/brother_ql/backends/linux_kernel.py", line 55, in _write
    os.write(self.write_dev, data)
OSError: [Errno 22] Invalid argument
```

Environment
```
Requirement already satisfied, skipping upgrade: attrs in /usr/local/lib/python3.7/dist-packages (from brother-ql==0.9.dev0) (21.4.0)
Requirement already satisfied, skipping upgrade: click in /usr/lib/python3/dist-packages (from brother-ql==0.9.dev0) (7.0)
Requirement already satisfied, skipping upgrade: future in /usr/local/lib/python3.7/dist-packages (from brother-ql==0.9.dev0) (0.18.2)
Requirement already satisfied, skipping upgrade: packbits in /usr/local/lib/python3.7/dist-packages (from brother-ql==0.9.dev0) (0.6)
Requirement already satisfied, skipping upgrade: pillow>=3.3.0 in /usr/lib/python3/dist-packages (from brother-ql==0.9.dev0) (5.4.1)
Requirement already satisfied, skipping upgrade: pyusb in /usr/local/lib/python3.7/dist-packages (from brother-ql==0.9.dev0) (1.0.2)
```

**Comment by brianFruit** [comment]
Resolved by reinstalling the raspbian OS. The printer is now detected in the /dev/usb/ path which is the proper printer identifier.
