### ISSUE TITLE
AssertionError on finish printing

### ISSUE THREAD

**Issue by chaoszcat** [pklaus/brother_ql#14]
Thanks for this cool library! It works almost perfect on my Raspberry Pi 3!

Anyway, I keep having this "AssesrtionError" prompting up after each successful printing. I wonder if it's my environment issue or the printer is not responding correctly?

- Printer is QL-700, USB connected to Raspberry Pi 3
- Installed this driver and as well as pyusb (I can't see lp in `/dev/usb`)
- `brother_ql_create -m QL-700 -s 62 /some/cat/image.png > test.bin`
- `brother_ql_print test.bin usb://0x04f9:0x2042`

After the print command, the image did printed on the label printer correctly, but in the console there is this assertion error:

    Traceback (most recent call last):
      File "/usr/local/bin/brother_ql_print", line 9, in <module>
        load_entry_point('brother-ql==0.7.4', 'console_scripts', 'brother_ql_print')()
      File "/usr/local/lib/python2.7/dist-packages/brother_ql/brother_ql_print.py", line 92, in main
        result = interpret_response(data)
      File "/usr/local/lib/python2.7/dist-packages/brother_ql/reader.py", line 153, in interpret_response
        assert data.startswith(b'\x80\x20\x42')
    AssertionError

Any idea?

**Comment by pklaus** [comment]
Hi chaoszcat,
sorry, it took me ages to respond to your report. Maybe I was assigning it a low priority (in my brain) because you stated that printing the label did work and the error only occurred afterwards.

Anyhow, if you could try again and this time add the command line parameter `--debug` to your brother_ql_print call. This would make the tool print the whole received sequence before failing.

**Comment by AngelSotomayor** [comment]
Hello @pklaus,
I have the same problem as the OP, but in my case it's not printing anything. I'm using Windows with the  libusb driver and i get this error:

INFO:brother_ql.brother_ql_print:Sending instructions to the printer. Total: 13722 bytes.
DEBUG:brother_ql.backends.generic:Writing 13722 bytes.
DEBUG:brother_ql.backends.generic:Read 118 bytes.
Traceback (most recent call last):
  File "C:\Users\Angel\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Angel\AppData\Local\Enthought\Canopy\App\appdata\canopy-1.7.4.3348.win-x86_64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "E:\Canopy\User\Scripts\brother_ql_print.exe\__main__.py", line 9, in <module>
  File "e:\canopy\user\lib\site-packages\brother_ql\brother_ql_print.py", line 98, in main
    result = interpret_response(data)
  File "e:\canopy\user\lib\site-packages\brother_ql\reader.py", line 156, in interpret_response
    assert data.startswith(b'\x80\x20\x42')
AssertionError

Do you have any idea of whats happening?
