### ISSUE TITLE
Error: Insufficient amount of data received

### ISSUE THREAD

**Issue by emdete** [pklaus/brother_ql#55]
When printing to my ql-1050 the program aborts after 2/3 of the image with:

```
brother_ql --backend pyusb --printer usb://0x04f9:0x2020 --model QL-1050 print --label 102x152 --dither /tmp/sample.png
INFO:brother_ql.backends.helpers:Sending instructions to the printer. Total: 274144 bytes.
Traceback (most recent call last):
  File "/usr/bin/brother_ql", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/brother_ql/cli.py", line 147, in print_cmd
    send(instructions=instructions, printer_identifier=printer, backend_identifier=backend, blocking=True)
  File "/usr/lib/python2.7/site-packages/brother_ql/backends/helpers.py", line 76, in send
    result = interpret_response(data)
  File "/usr/lib/python2.7/site-packages/brother_ql/reader.py", line 157, in interpret_response
    raise NameError('Insufficient amount of data received', hex_format(data))
NameError: ('Insufficient amount of data received', '61 72 72 61 79 28 27 42 27 29')
```

the printer is stuck, wont cut or feed until switched of & on again.

**Comment by raat1979** [comment]
Hold pwr button to Turn off?
