### ISSUE TITLE
QL-800 29mm Sample Roll Error

### ISSUE THREAD

**Issue by jtrexr2** [pklaus/brother_ql#75]
Hello, I have application printing QR labels on the QL-800 included 62mm black/red endless roll without issue. However, I tried to change to the also-included 29mm endless roll included with the QL-800, and get the following error:
```
brother_ql --backend pyusb --model QL-800 --printer usb://0x04f9:0x209b  print --red -l 29 qr.png
WARNING:brother_ql.conversion:Need to resize the image...
INFO:brother_ql.backends.helpers:Sending instructions to the printer. Total: 57160 bytes.
Traceback (most recent call last):
  File "C:\Python27\Scripts\brother_ql-script.py", line 11, in <module>
    load_entry_point('brother-ql==0.9.dev0', 'console_scripts', 'brother_ql')()
  File "c:\python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\brother_ql\cli.py", line 147, in print_cmd
    send(instructions=instructions, printer_identifier=printer, backend_identifier=backend, blocking=True)
  File "c:\python27\lib\site-packages\brother_ql\backends\helpers.py", line 76, in send
    result = interpret_response(data)
  File "c:\python27\lib\site-packages\brother_ql\reader.py", line 164, in interpret_response
    raise NameError("Printer response doesn't start with the usual header (80:20:42)", hex_format(data))
NameError: ("Printer response doesn't start with the usual header (80:20:42)", '61 72 72 61 79 28 27 42 27 2C 20 5B 31 32 38 2C 20 33 32 2C 20 36 36 2C 20 35 32 2C 20 35 36 2C 20 34 38 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 32 39 2C 20 31 31 2C 20 30 2C 20 30 2C 20 31 2C 20 30 2C 20 30 2C 20 39 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 31 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 2C 20 30 5D 29')
```

My environment is as follows: 
```
##################

Information about the running environment of brother_ql.
(Please provide this information when reporting any issue.)

About the computer:
  * Platform: Windows-10-10.0.18362
  * Processor: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
  * Release: 10
  * System: Windows
  * Machine: AMD64
  * Architecture: ('64bit', 'WindowsPE')
About the installed Python version:
  * 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
About the brother_ql package:
  * package location: c:\python27\lib\site-packages
  * package version:  0.9.dev0
  * brother_ql CLI path: unknown
About the requirements of brother_ql:
  requirement    | requested  | installed version
  -------------- | ---------- | -----------------
  attrs          | any        | 19.3.0
  click          | any        | 7.0
  enum34         | any        | 1.1.6
  future         | any        | 0.18.2
  packbits       | any        | 0.6
  pillow         | >= 3.3.0   | 6.2.1
  pyusb          | any        | 1.0.2
  typing         | any        | 3.7.4.1

##################
```

I appreciate your help!

**Comment by jtrexr2** [comment]
Found my problem, wasn't paying enough attention. The supplied 29mm roll should be `29x90` in the command for the `--label_size` parameter.
